'use strict';
const characters = [
 {name:'복숭아 강아지',emoji:'🐶',quote:'너도 와! 같이 하면 더 재밌잖아!',desc:'사람이 모이면 에너지가 생기는 마을의 초대 담당. 좋은 일이 생기면 혼자 좋아하기 아까워요.',quirk:'모두를 챙겨놓고 집에 가서는 “나 오늘 너무 떠들었나?” 생각해요.',love:'좋아하는 티가 말과 표정에 묻어나요. 반응이 돌아오면 더 신나요.',work:'첫 대화와 아이디어 회의를 열어요. 마무리 약속을 잡아두면 더 잘 달려요.',friend:'“지금 잠깐 나올래?”가 가능한 번개 친구.',charge:'네가 와서 분위기가 좋아졌어!'},
 {name:'딸기 토끼',emoji:'🐰',quote:'너 이거 좋아한다고 했잖아!',desc:'생일과 취향을 기억하는 다정한 약속 요정. 함께하는 시간이 즐겁도록 미리 작은 준비를 해요.',quirk:'“아무거나 괜찮아!”라고 했지만 저장한 맛집은 이미 다섯 곳.',love:'작은 기념일과 둘만의 습관을 소중히 여겨요.',work:'사람과 일정을 함께 챙겨요. 부탁을 너무 많이 맡지 않도록 경계선도 필요해요.',friend:'모임 끝나고 “잘 들어갔어?”를 보내는 친구.',charge:'네가 챙겨준 거, 나 기억하고 있어.'},
 {name:'젤리 수달',emoji:'🦦',quote:'재밌겠는데? 일단 내가 해볼게!',desc:'새로운 걸 발견하면 직접 만져보는 행동파. 어색한 분위기도 함께할 활동 하나로 풀어버려요.',quirk:'잠깐 구경하러 갔다가 체험 수업까지 듣고 와요.',love:'같이 경험하고 웃으면서 가까워져요.',work:'막힌 일에 첫 시도를 만들어요. 시작한 일을 공유하면 동료들이 따라오기 쉬워요.',friend:'취미 체험과 당일치기 여행의 단짝.',charge:'너랑 하면 처음 하는 것도 덜 어렵다!'},
 {name:'꿀단지 곰',emoji:'🐻',quote:'일단 밥 먹자. 그다음 같이 해결하자.',desc:'마음이 쓰이면 실제로 도와주는 마을의 든든한 주민. 약속한 일은 잘 끝내고 싶어요.',quirk:'본인은 무심하다고 생각하지만 남의 충전기까지 챙겨 다녀요.',love:'꾸준한 연락과 실질적인 배려로 마음을 보여줘요.',work:'역할을 나누고 일을 끝까지 끌고 가요. 해결 전에 상대 의견을 물으면 더 좋아요.',friend:'곤란할 때 전화하면 함께 방법을 찾아주는 친구.',charge:'덕분에 마음이 놓였어.'},
 {name:'솜사탕 고양이',emoji:'🐱',quote:'조용히 같이 있어도 좋잖아.',desc:'자기 속도로 가까워지며 소소한 분위기를 즐겨요. 편해진 사람에게는 엉뚱한 농담과 취향을 잔뜩 꺼내놓아요.',quirk:'단체 채팅방에서는 조용한데 친한 친구에게는 밈 열두 개 전송.',love:'부담 없이 함께하는 시간 속에서 마음이 열려요.',work:'혼자 생각할 시간을 얻으면 섬세한 의견을 보태요.',friend:'목적 없이 걷고 각자 할 일을 해도 편한 친구.',charge:'천천히 말해도 돼. 듣고 있어.'},
 {name:'푸딩 펭귄',emoji:'🐧',quote:'우리 다음에도 여기 올까?',desc:'익숙한 사람과 쌓는 작은 추억을 좋아해요. 눈에 잘 띄지 않는 배려를 오래 기억합니다.',quirk:'새 메뉴를 고민하는 척하다가 늘 먹던 최애 메뉴를 주문해요.',love:'일정하고 다정한 표현에서 편안함을 느껴요.',work:'미리 준비하고 꼼꼼히 살펴요. 갑작스러운 변경은 조금 일찍 알려주면 좋아요.',friend:'몇 달 만에 만나도 어제 본 것 같은 오래가는 친구.',charge:'우리 약속, 나도 소중해.'},
 {name:'귤 여우',emoji:'🦊',quote:'더 간단한 방법이 있을 것 같은데?',desc:'혼자 탐색하다가 뜻밖의 해결책을 들고 나타나요. 방식은 유연하지만 쓸모가 있는지는 직접 확인하고 싶어요.',quirk:'관심 없는 주제에는 말이 없다가 취향 이야기가 나오면 갑자기 해설자.',love:'서로의 취향과 시간을 존중하면서 가까워져요.',work:'재량이 있으면 새로운 해결책을 찾아요. 중간 상황도 알려주면 협업이 편해져요.',friend:'신기한 장소와 숨은 취미를 알려주는 친구.',charge:'네 방식이 궁금해. 보여줄래?'},
 {name:'쿠키 햄스터',emoji:'🐹',quote:'혹시 몰라서 하나 더 챙겼어.',desc:'작은 준비로 큰 혼란을 막는 마을의 살림꾼. 드러내지 않아도 주변을 꽤 자세히 보고 있어요.',quirk:'가방에서 밴드, 간식, 보조배터리가 차례대로 나와요.',love:'말한 것을 기억하고 약속을 지키며 애정을 표현해요.',work:'빠진 부분을 발견하고 완성도를 높여요. 필요한 기준이 명확하면 편해요.',friend:'여행 준비물과 정산을 믿고 맡길 수 있는 친구.',charge:'네가 신경 쓴 부분 덕분에 잘됐어.'}
];
const questions = [
 ['단체 채팅방에 “우리 언제 한번 봐요!”가 올라왔다.','“다음 주 금요일 어때요?” 일단 약속을 움직인다.','올라오는 이야기를 보다가 마음에 드는 약속에 합류한다.'],
 ['친구가 “나 오늘 좀 속상했어”라고 말한다.','“무슨 일이야ㅠㅠ” 마음부터 충분히 들어준다.','“어떤 상황이었어?” 같이 해결할 방법을 찾아본다.'],
 ['처음 가는 동네에서 약속까지 한 시간 남았다.','골목을 걸으며 끌리는 곳에 들어간다.','저장해둔 곳이나 후기가 좋은 곳을 찾아간다.'],
 ['회의에서 재밌는 아이디어가 떠올랐다.','말하면서 동료들과 함께 발전시킨다.','잠깐 정리한 다음 내 생각을 꺼낸다.'],
 ['좋아하는 사람을 위해 더 자연스럽게 하는 행동은?','다정한 메시지를 보내고 작은 변화도 알아봐준다.','필요한 걸 챙겨주고 번거로운 일을 도와준다.'],
 ['친구들과 떠나는 주말 여행! 더 설레는 일정은?','핵심 하나만 정하고 나머지는 마음 가는 대로.','가고 싶은 곳을 골라 여유 있게 짜둔 일정.'],
 ['팀에 새 멤버가 들어왔다.','먼저 말을 걸고 함께할 자리를 만든다.','필요한 순간에 편하게 물어볼 수 있도록 곁을 내준다.'],
 ['프로젝트를 마친 뒤 듣고 싶은 칭찬은?','“덕분에 함께하는 시간이 참 좋았어요.”','“덕분에 일이 잘 풀렸어요.”']
];
const app=document.getElementById('app');
let answers=[],step=0,resultId=0,partner=1,mode='work',hasResult=false;
function animal(id,cls=''){return `<div class="animal ${cls}" role="img" aria-label="${characters[id].name}" style="background-size:${1536/[425,335,360,356,407,329,400,346][id]*100}% 200%;background-position:${[0,445,795,1180,0,430,780,1190][id]/(1536-[425,335,360,356,407,329,400,346][id])*100}% ${id<4?0:100}%"></div>`;}
function screen(html){app.innerHTML=html;window.scrollTo({top:0,behavior:'instant'});const title=app.querySelector('h1,h2');if(title){title.setAttribute('tabindex','-1');title.focus({preventScroll:true});}}
function home(){screen(`<section class="card"><p class="eyebrow">A LITTLE QUIZ, A LITTLE CLOSER</p><h1>나는 어떤 동물 친구일까?</h1><p class="intro">연애할 때, 일할 때, 놀 때.<br>여덟 번의 작은 선택으로 만나는 나의 말랑한 모습.</p><div style="margin-top:13px"><span class="pill">✦ 8문항</span><span class="pill">약 2분</span><span class="pill">정답은 없어요</span></div><div class="cast">${characters.map((c,i)=>`<div>${animal(i)}<p class="mini-name">${c.name}</p></div>`).join('')}</div><button class="primary wide" id="start">나의 동물 친구 만나기 →</button><p class="meta">가장 나다운 답을 골라주세요.</p><button class="text-button" id="browse">마을 친구들 먼저 구경하기 ↗</button></section>`);document.getElementById('start').onclick=()=>{answers=[];hasResult=false;step=0;quiz();};document.getElementById('browse').onclick=directory;}
function quiz(){const q=questions[step];screen(`<section class="card question-card"><div class="progress-row"><span>나를 알아가는 중</span><span>${step+1} / 8</span></div><progress value="${step}" max="8" aria-label="완료한 질문"></progress><div class="question-animal">${animal(step)}</div><p class="eyebrow">QUESTION ${String(step+1).padStart(2,'0')}</p><h2>${q[0]}</h2><div class="options">${q.slice(1).map((v,i)=>`<button class="option ${answers[step]===i?'selected':''}" data-answer="${i}"><b>${i?'B':'A'}</b><span>${v}</span></button>`).join('')}</div><div class="question-bottom"><button class="text-button" id="prev" ${step===0?'disabled':''}>← 이전 질문</button><span>둘 다 맞으면 첫 느낌으로!</span><button class="text-button" id="exit">처음으로</button></div></section>`);app.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{answers[step]=Number(b.dataset.answer);if(step===7){resultId=score(answers);partner=(resultId+1)%8;hasResult=true;result();}else{step++;quiz();}});document.getElementById('prev').onclick=()=>{if(step>0){step--;quiz();}};document.getElementById('exit').onclick=home;}
function score(a){const social=[0,3,6].reduce((s,i)=>s+a[i],0)>=2?1:0;const care=[1,4,7].reduce((s,i)=>s+a[i],0)>=2?1:0;const plan=a[2];return social*4+care*2+plan;}
function traits(id){return [id<4?'☀️ 햇살':'🌙 달빛',(id%4)<2?'💗 다정':'🧰 든든',id%2?'🧺 소풍':'🎈 산책'];}
function result(preview=false){const c=characters[resultId];screen(`<section class="card"><p class="eyebrow">${preview?'MEET THE RESIDENTS':'YOUR MALLANG FRIEND'}</p><div class="result-top"><div class="result-art">${animal(resultId)}</div><div><p class="meta">${preview?'이 친구를 소개할게요':'당신의 말랑마을 캐릭터는'}</p><h1>${c.name}</h1><div class="traits">${traits(resultId).map(t=>`<span class="pill">${t}</span>`).join('')}</div><p class="quote">“${c.quote}”</p><p class="description">${c.desc}</p></div></div><div class="quirk">🤭 귀여운 반전 · ${c.quirk}</div><div class="mode-grid"><div class="mode"><h3>💼 일할 때의 나</h3><p>${c.work}</p></div><div class="mode"><h3>🍿 친구일 때의 나</h3><p>${c.friend}</p></div><div class="mode"><h3>💌 연애할 때의 나</h3><p>${c.love}</p></div></div><div class="charge">🔋 나의 충전 버튼<br><strong>“${c.charge}”</strong></div><div class="divider"></div><h2 class="section-title">우리 둘은 어떤 케미일까?</h2><p class="intro">상대의 캐릭터를 골라 작은 차이를 발견해요.</p><div class="tabs" role="group" aria-label="궁합 종류">${[['work','💼 업무'],['friend','🍿 친구'],['love','💌 연애']].map(([id,label])=>`<button class="tab ${mode===id?'active':''}" aria-pressed="${mode===id}" data-mode="${id}">${label} 궁합</button>`).join('')}</div><div class="partner-row"><label for="partner">함께 볼 친구</label><select id="partner">${characters.map((x,i)=>`<option value="${i}" ${partner===i?'selected':''}>${x.emoji} ${x.name}</option>`).join('')}</select></div><div id="chemistry" aria-live="polite"></div><p class="team-tip">팀에서 해보기 · 각자 결과를 찾고 옆 사람과 업무·친구 궁합을 확인해요.<br>“나와 함께할 때는 ___ 해주면 좋아요!” 한마디씩 나눠보세요.<br>연애 궁합은 원하는 사람만 가볍게 즐겨요.</p><div class="actions"><button class="secondary" id="again">${preview?'나도 테스트하기':'다시 테스트하기'}</button><button class="secondary" id="all">다른 친구 구경하기</button></div>${!preview&&answers[2]!==answers[5]?'<p class="meta">산책·소풍 답변이 같아서 3번 답으로 골랐어요. 두 성향 모두 읽어보세요.</p>':''}</section>`);document.getElementById('partner').onchange=e=>{partner=Number(e.target.value);chemistry();};app.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;app.querySelectorAll('[data-mode]').forEach(t=>{t.classList.toggle('active',t.dataset.mode===mode);t.setAttribute('aria-pressed',t.dataset.mode===mode);});chemistry();});document.getElementById('again').onclick=()=>{answers=[];hasResult=false;step=0;quiz();};document.getElementById('all').onclick=directory;chemistry();}
const pairs={
 work:[['🚀 일단 출발 연구소','새로운 시도가 잘 나오는 조합이에요. 마감과 완료 기준을 먼저 적어두면 아이디어가 결과로 이어져요.'],['🧱 차곡차곡 제작소','준비와 실행 약속을 맞추기 편한 조합이에요. 새로운 방법을 시험할 자리도 조금 남겨두세요.'],['🪁 연과 연줄 제작소','가능성과 실행 조건을 함께 볼 수 있어요. 자유롭게 바꿔도 되는 범위와 지켜야 할 약속을 정해두세요.']],
 friend:[['🎤 예능 한 편 뚝딱','만나면 이야기가 계속 나오는 조합이에요. 서로의 이야기를 끝까지 들어주면 둘 다 주인공!'],['🛋️ 무언의 소파 동맹','각자 있어도 함께라서 좋아요. 보고 싶을 땐 먼저 연락해보세요. 조용한 초대도 충분해요.'],['🌻 햇볕 드는 창가','먼저 초대하는 즐거움과 편하게 머무는 즐거움이 만나요. 거절도 편하게 할 수 있도록 해주세요.']],
 love:[['🍓 딸기우유 커플','마음 표현이 풍성한 조합이에요. 원하는 건 눈치 대신 말로도 알려주세요. 다정함에도 자막이 필요하니까요.'],['🍞 갓 구운 토스트 커플','행동으로 서로를 챙기는 조합이에요. 가끔은 “좋아해”라는 자막도 붙여주세요.'],['🍫 코코아와 마시멜로 커플','표현 방법이 달라 발견하는 재미가 있어요. “들어줄까, 도와줄까?”를 먼저 물어보세요.']]
};
function pairIndex(a,b){return a===b?a:2;}
function getChemistry(a,b,m){const axis=m==='work'?1:m==='friend'?4:2;const bit=x=>Math.floor(x/axis)%2;return pairs[m][pairIndex(bit(a),bit(b))];}
function chemistry(){const [title,text]=getChemistry(resultId,partner,mode);const social=pairIndex(resultId<4?0:1,partner<4?0:1);const plan=pairIndex(resultId%2,partner%2);const bonus=mode==='work'?['말하면서 발전시키는 조합. 마지막 2분은 결정 사항 적기!','생각을 정리해서 나누는 조합. 공유할 시간을 정해두기!','대화와 생각할 시간을 번갈아 쓰기. 회의 주제는 미리 알려주기!'][social]:['발길 따라 떠나는 랜덤 산책단. 예약 하나는 확인하기!','기다리는 순간부터 즐거운 위시리스트 동맹. 계획이 틀어져도 서로 탓하지 않기!','목적지는 정하고 골목은 자유롭게. 필수 일정 하나만 함께 정하기!'][plan];document.getElementById('chemistry').innerHTML=`<div class="compat"><div class="pair">${animal(resultId)}<span class="pair-symbol">${mode==='love'?'♡':'＋'}</span>${animal(partner)}</div><h3>${title}</h3><p>${text}</p><p class="bonus">✦ ${bonus}</p></div>`;}
function directory(){const saved=resultId;screen(`<section class="card"><p class="eyebrow">OUR LITTLE NEIGHBORS</p><h1>말랑마을의 여덟 친구</h1><p class="intro">궁금한 친구를 눌러 이야기를 만나보세요.</p><div class="directory">${characters.map((c,i)=>`<button class="resident" data-resident="${i}">${animal(i)}<strong>${c.name}</strong></button>`).join('')}</div><button class="secondary" id="back">${hasResult?'내 결과로 돌아가기':'처음으로'}</button></section>`);app.querySelectorAll('[data-resident]').forEach(b=>b.onclick=()=>{resultId=Number(b.dataset.resident);result(true);});document.getElementById('back').onclick=()=>{resultId=hasResult?score(answers):saved;hasResult?result():home();};}
home();
